### ISSUE TITLE
Does not work with background mode

### ISSUE THREAD

**Issue by chrishoage** [jo-sm/SublimeLinter-contrib-stylelint_d#2]
I have my liter set to lint in background mode. This works fine with `eslint_d` because they allow input to be passed in with `stdin`. 

https://github.com/roadhump/SublimeLinter-contrib-eslint_d/blob/master/linter.py

I suspect this has to do with `self.filename` in `communicate` but am not certain

**Comment by jo-sm** [comment]
Linking the `stylelnt_d` issue here for cross-referencing: https://github.com/jo-sm/stylelint_d/issues/3

**Comment by jo-sm** [comment]
Hey @chrishoage, I updated the plugin to support `stdin` via the `--stdin` flag. You'll need to upgrade to `stylelint_d` version `1.0.5`, then update this plugin. After that it should work! 🎉
