### ISSUE TITLE
Incomplete regex

### ISSUE THREAD

**Issue by woble** [jo-sm/SublimeLinter-contrib-stylelint_d#3]
Should be as follows to respect warnings as well as errors, currently rules with warning severity are shown as errors; implementation (from SublimeLinter-contrib-stylelint) is incomplete.

`r'^\s*(?P<line>\d+)\:(?P<col>\d+)\s*(?:(?P<error>\u00D7|\u2716)|(?P<warning>\u203C|\u26A0))\s*(?P<message>.+)'`

Took me and a colleague a while to figure something so obvious, but apparently stylelint uses different unicodes for warning and error on Windows and Mac.

If you haven't yet, you should submit this to packagecontrol.io as this is way better than SublimeLinter-contrib-stylelint.

**Comment by jo-sm** [comment]
I'm guessing that Windows and Mac/Unix have different Unicode characters for `✖` and `⚠`. Ideally we shouldn't have a regex for specific Unicode characters since that seems a little brittle, but with the current `stylelint` there's not much that can be done because they only output Unicode rather than the string "warning" or "error". 

I'll see if I can get this fixed in `stylelint` proper and make a regex that only uses text. 

Also, yes, I submitted to PackageControl but I think the person who handles it is out on vacation right now...

**Comment by woble** [comment]
Valid point. However it's not stylelint issue per se. They use [log-symbols](https://github.com/sindresorhus/log-symbols) which states that Windows has a limitation when it comes to these characters.

**Comment by jo-sm** [comment]
That's true, but my thinking is that if you're using the linter programmatically, e.g. in this plugin, you don't care about seeing that symbol and the regex is a little obtuse to understand (e.g. someone who sees the code would not know why that Unicode character refers to warning immediately).

**Comment by woble** [comment]
It's true that you don't care about seeing those symbols in the editor, but you still need a way to catch errors and warning for SublimeLinter to process it correctly. Maybe I am missing something but I don't really see any other way around it other than catching those chars. Whether the regex uses actual character or its unicode value (less readable but a bit safer imho) doesn't really matter to me.

**Comment by jo-sm** [comment]
Agreed. I made a PR in `stylelint` allowing for no unicode chars in the string formatter, once that gets merged I'll update the plugin to the latest and add a regex that supports warnings and errors.

**Comment by jo-sm** [comment]
@woble I updated the plugin to correctly parse warnings and errors, see 1fe7c0f105e680ab7109d9ad79b03cb1c5a8991e. You'll need to update to the latest `stylelint_d`, restart the server, and update this plugin, and it should work.

**Comment by woble** [comment]
All seems to work! 👍
