### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by jo-sm** [jo-sm/SublimeLinter-contrib-stylelint_d#4]
From https://github.com/jo-sm/stylelint_d/issues/5#issuecomment-239613914.

> Hmm, I am not sure if it's Windows 7, or something on my work machine (maybe antivirus; can't disable it unfortunately because corp policy) but I can't seem to get `stylelint_d` to work any more.
> #### Things I've tried
> - Reinstalling nodejs (LTS version) and some of the global packages that I use.
> - Fresh Sublime Text 3 (Dev 3120) with only a few required packages, `SublimeLinter`, `SublimeLinter-contrib-tslint`, `SublimeLinter-contrib-stylelint_d`, `Syntax Highlighting for PostCSS`, `TypeScript`.
> - Also installed `SublimeLinter-contrib-stylelint` to test if it breaks anything.
> #### Observed behavior
> - Run `stylelint_d start`.
> - Open ST project with linters (`tslint`, `stylelint_d`) setup through the project file.
> - No files are open. SublimeLinter is in debug mode.
> - Open `.ts` file — `tslint` initiated. Linting works and there's output in Sublime console.
> - Open `.pcss` file — `stylelint_d` initiated. Linting doesn't work and no console output.
> - Switch to the open `.ts` file. Linting doesn't work. No console output.
> 
> It looks as if the moment `stylelint_d` is run once, SublimeLinter stops working without any errors or dumps in console.
> 
> Swapping `stylelint_d` for `stylelint` in the same scenario works just fine.
> 
> EDIT:
> I just realized that this might be related to the ST plugin rather than `stylelint_d` itself. Running `cat foo.css | stylelint_d --stdin --config stylelint.json` or `stylelint_d foo.css --config stylelint.json` returns expected listing errors.

**Comment by jo-sm** [comment]
@woble can you paste the output from the debug console of a sample linting session in Sublime with this plugin? Also, can you run `stylelint_d --version` and tell me what version of the plugin you're using?

**Comment by woble** [comment]
Version is `1.0.8` as it should be since I did a fresh install. One thing that seems to occur randomly (I can't repduce it) is that it does work on the first load and then stops. But most of the time, after restarting ST, you would just see the first line from the following snippet and then.

```
SublimeLinter: stylelint_d: index.pcss ['C:\\Users\\user\\AppData\\Roaming\\npm\\stylelint_d.cmd', '--stdin', '--formatter=json', '--file', '@', '--config', 'D:/Git/project/.sublimetext/../build/plugins/gulp-stylelint/stylelint.json'] 
SublimeLinter: stylelint_d output:
124:26 warning Do not use !important unless really neccessary 
SublimeLinter: stylelint_d: index.pcss ['C:\\Users\\user\\AppData\\Roaming\\npm\\stylelint_d.cmd', '--stdin', '--formatter=json', '--file', '@', '--config', 'D:/Git/project/.sublimetext/../build/plugins/gulp-stylelint/stylelint.json'] 
```

I did some comparing of processes between W7 and W10 and I am observing the following.
- On Windows 7, regardless whether the daemon is running or not, `stylelint_d` always gets loaded as a child of ST process and does not get terminated. I assume that's why sometimes it does lint, but only once.
- On Windows 10, if the daemon is not running on the system, the daemon is started, ST passes the command and kills its own process and leaves daemon running. Expected behaviour.

![stylelint_d-w7-w10](https://cloud.githubusercontent.com/assets/494873/17643600/4acf0ffa-616f-11e6-82ad-ecf763bf68be.png)
- Second `node.exe` on W7 is `stylelint_d\lib\server.js`, which shouldn't be running as a child process of ST. First node.exe is the command that is being passed on to the daemon. A wild guess, but because the first `node.exe` process is never terminated, SublimeLinter is just sitting there waiting for something to finish? 😕 
- On W10, `stylelint_d\lib\server.js` is its own process (not shown in the image). That `node.exe` is for `tsserver.js` btw. Process that passes on `--stdin --file ...` parameters is short lived.

Hope that helps a little bit.

**Comment by jo-sm** [comment]
Hmm, your plugin and `stylelint_d` versions are correct, so maybe it is a W7 + Sublime/SublimeLinter issue. I would guess you're right and the `stylelint_d` client isn't getting terminated properly on Windows 7, and I'm guessing that because it's not being terminated the linter just hangs thinking that the original process never finished, and doesn't try to spawn a new one or pipes the commands to that process that just hangs.

I don't think that the server running as a child of the Sublime process would be an issue, since it should accept connections regardless, so my wild guess is that it's a problem with how either Sublime or SublimeLinter handles spawning processes with Node. 

One thing I can do is make a debug mode for `stylelint_d`, which would output various debugging info to stdout, which may be helpful in determining how the process flow is handled on Windows 7. What happens if you start the server manually outside of Sublime, and then open and try to lint in Sublime on W7? If it's spawning a server as a child, it should fail because the port is being used by the server you started manually.

**Comment by woble** [comment]
When `stylelint_d` is started manually, the process is running as it should. The moment SublimeLinter kicks in, it hi-jacks that service as shown in previous image and waits.

Also, killing those processes produces the following message in ST console.

```
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "D:\Programs\Sublime Text 3\Data\Packages\SublimeLinter\lint\queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/json/decoder.py", line 367, in raw_decode
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Programs\Sublime Text 3\Data\Packages\SublimeLinter\lint\queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "D:\Programs\Sublime Text 3\Data\Packages\SublimeLinter\lint\queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "D:\Programs\Sublime Text 3\Data\Packages\SublimeLinter\sublimelinter.py", line 119, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "D:\Programs\Sublime Text 3\Data\Packages\SublimeLinter\lint\linter.py", line 929, in lint_view
    linter.lint(hit_time)
  File "D:\Programs\Sublime Text 3\Data\Packages\SublimeLinter\lint\node_linter.py", line 77, in lint
    super(NodeLinter, self).lint(hit_time)
  File "D:\Programs\Sublime Text 3\Data\Packages\SublimeLinter\lint\linter.py", line 1397, in lint
    output = self.run(cmd, self.code)
  File "D:\Programs\Sublime Text 3\Data\Packages\SublimeLinter-contrib-stylelint_d\linter.py", line 49, in run
    parsed = json.loads(raw)
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 369, in raw_decode
ValueError: No JSON object could be decoded

SublimeLinter: -------------------- 
```

I am going to try eslint_d today or tomorrow and see if that works on W7, assuming it uses similar approach as your daemon.

**Comment by woble** [comment]
Tried `eslint_d` and both W7 and W10 work without a problem.

**Comment by jo-sm** [comment]
I wonder if it's this... https://github.com/jo-sm/SublimeLinter-contrib-stylelint_d/blob/master/linter.py#L48

**Comment by jo-sm** [comment]
@woble Can you change the `linter.py` code to do the following and let me know if it works?
1. Change regex to :

```
regex = (
    r'^\s*(?P<line>\d+)\:(?P<col>\d+)\s*(?:(?P<error>\u00D7|\u2716)|(?P<warning>\u203C|\u26A0))\s*(?P<message>.+)'
)
```
1. Comment out the `def run()` code.

That will at least boil it down to the `run` method if so.

**Comment by woble** [comment]
Still nothing. Managed to get it working 2 times, but it only runs once as before and then gets stuck.

**Comment by jo-sm** [comment]
Let me see if I can test this on a Windows 7 VM.

**Comment by jo-sm** [comment]
Hey @woble can you update to the latest plugin?

**Comment by woble** [comment]
I am afraid it's still the same as before.

**Comment by jo-sm** [comment]
It should tell you some error in the console now... The issue was that the plugin wasn't wrapping JSON parsing in a try/except block, so if the error wasn't JSON (which non-stylelint lint errors are e.g. if a configuration is missing) it wouldn't handle it properly. Is there anything in the debug console?

**Comment by woble** [comment]
Updated, made sure no old stuck processes are running. But, again nothing of the sort in the console, except the usual:

`SublimeLinter: stylelint_d: index.pcss ['C:\\Users\\user\\AppData\\Roaming\\npm\\stylelint_d.cmd', '--stdin', '--formatter=json', '--file', '@', '--config', 'D:/Git/project/.sublimetext/../build/plugins/gulp-stylelint/stylelint.json']`

**Comment by jo-sm** [comment]
Hmm... on my testing VM in Windows 7, it takes a moment but the linter does eventually run and give me errors (or tell me my config is missing, if I force it). Can you double check everything?

~~Also, are you editing the plugin to include the `--config` flag? If so, I can see what it would take to add the config parameter to the package settings.~~ Nevermind, I didn't know you could specify additional arguments in the config by default.

**Comment by woble** [comment]
I've done that several times before and just now again, the result is the same. I am clueless at the moment. 😕 

If I find time tomorrow, I will try testing it on some of my co-workers machines since they run similar setup.

**Comment by jo-sm** [comment]
Okay, let me know -- I tested on a fresh 32-bit Windows 7 VM (the IE 11 Windows 7 VM from [modern.ie](https://modern.ie)) and after figuring out I was missing the try/except block it did work. 

For reference, I installed the Node version `4.4.7` from [nodejs.org](https://nodejs.org), `stylelint_d` version `1.0.8` via `npm`, Sublime Text version `3114`, Package Control, `SublimeLinter-contrib-stylelint_d` version `v2016.08.14.09.39`.

**Comment by woble** [comment]
@jo-sm
Tried it on another work machine and the result is nearly the same. It worked for a brief moment and then stopped with the same result as I described previously, i.e. processes waiting for something to finish.

**Comment by jo-sm** [comment]
Do you have access to a non-work Windows 7 computer? It may be a configuration issue with the computer(s) itself. I looked at the process tree using Process Explorer and found that the Node server was spawned outside of Sublime, and the `plugin_host.exe` process handled piping commands to `stylelint_d.cmd`, so if that's not the case locally then it could be something else going on.

Here is some sample output:

```
SublimeLinter: stylelint_d: test.css ['C:\\Users\\IEUser\\AppData\\Roaming\\npm\\stylelint_d.cmd', '--stdin', '--formatter=json', '--file', '@'] 
SublimeLinter: stylelint_d output:
296:2 error Expected newline after "}" (block-closing-brace-newline-after)
5:52 error Expected newline before "}" (block-closing-brace-newline-before)
6:54 error Expected newline before "}" (block-closing-brace-newline-before)
... (truncated output)
```

**Comment by woble** [comment]
It must be the configuration as I tried it in VM yesterday and everything worked as expected. I even tried running my work machine in safe mode, which disables some of the processes but the result is all the same: works once and then no more.

I can't really think of anything that could be causing the processes behave differently, other than maybe the antivirus software. Yet again, why does it not affect `eslint_d` for example. :confused: 

I guess I will be rolling back to `stylelint` for now to at least have some linting.

**Comment by jo-sm** [comment]
One thing I can think of is that it could be something with your work's Windows policies (which I think persist even in safe mode), but it's been a really long time since I've done any serious Windows work that it's a really wild guess. I'm sorry I can't help more than that... 

Did it work correctly before the change I made to support JSON? E.g. when the regex was incorrect, did it work as expected (barring obvious warning/error ambiguity)? I did fix the JSON try/catch issue, but there may be something else going on in there.

In any case, since I can't reproduce it, I'm going to close this for now; if you figure out the cause, please comment, since I'm sure you're not going to be the only Windows 7 user going forward. I'd hate to not have someone use it if it can be fixed on my end.

**Comment by woble** [comment]
I don't believe it ever worked properly, at least on my work machine. Originally there's was issue with the socket with `stylelint_d`. When that was fixed, it worked in Sublime only once before it stuck and tasks had to be terminated.

**Comment by jo-sm** [comment]
I would say then that it's likely a work machine configuration, especially since it also didn't work on a coworker's machine. I don't know why it would be antivirus -- the server binds to a specific port, but it doesn't do anything that I would characterize as potentially nefarious -- but it's worth investigating. I'm thinking it's probably a compute policy in place, though, especially if your personal computers you used to test also have antivirus.

**Comment by woble** [comment]
Maybe it has something to do with the port, so maybe try different port?

**Comment by jo-sm** [comment]
I doubt it... It uses port `48126` which is unassigned by IANA. If there's issues with the port it's not because of the client/server.

**Comment by woble** [comment]
Hmm. Using https://github.com/kungfusheep/SublimeLinter-contrib-stylelint/pull/49 from `SublimeLinter-contrib-stylelint`, changing `stylelint` to `stylelint_d` seems now to work on my corp W7 machine. Go figure. 😕
