### ISSUE TITLE
Unstable and also not loading settings from .stylelintrc

### ISSUE THREAD

**Issue by sethstha** [jo-sm/SublimeLinter-contrib-stylelint_d#6]
I was looking for fast stylelint alternative as it is too slow. 
This plugin is god to me but unfortunately, it is not stable also not working as expected

Have a look at here once i type 60 it shows error and after providing px it freezes. After then nothing seems to work. I have to restart sublime text.
![image](https://cloud.githubusercontent.com/assets/2367137/23408764/61b6ddbe-fdf1-11e6-8e79-c80c8c09d211.png)

And I am also eager to know why it is not loading my .stylelintrc file

Thank you

**Comment by jo-sm** [comment]
Can you tell me if there are any errors when you run that command in the Sublime console, by pressing `ctrl-<tilde>`? It should give something like this:

```
SublimeLinter: stylelint_d: index.css ['node_modules/.bin/stylelint_d', '--stdin', '--formatter=json', '--file', '@'] 
SublimeLinter: stylelint_d output:
247:10 error Unexpected unit "px" (unit-whitelist)
248:11 error Unexpected unit "px" (unit-whitelist) 
```

**Comment by sethstha** [comment]
Hi jo-sm,

I am getting this on sublime console.
```
SublimeLinter: stylelint_d: _search.scss ['C:\\xampp\\htdocs\\suffice\\wp-content\\themes\\suffice\\node_modules\\.bin\\stylelint_d.cmd', '--stdin', '--formatter=json', '--file', '@'] 
SublimeLinter: stylelint_d: _search.scss ['C:\\xampp\\htdocs\\suffice\\wp-content\\themes\\suffice\\node_modules\\.bin\\stylelint_d.cmd', '--stdin', '--formatter=json', '--file', '@']
``` 
It looks like stylelint_d command is not responding after few seconds. I have tried to run stylelint_d from command and it also freezes there. Have a look at here.
![image](https://cloud.githubusercontent.com/assets/2367137/23445478/d7027dc2-fe63-11e6-8f5b-8ec93db7a09d.png)

Again, when i restart sublime text. It starts to work for a few minutes. Look at this console log.

```
SublimeLinter: stylelint_d: _search.scss ['C:\\xampp\\htdocs\\suffice\\wp-content\\themes\\suffice\\node_modules\\.bin\\stylelint_d.cmd', '--stdin', '--formatter=json', '--file', '@'] 
SublimeLinter: stylelint_d output:
92:20 error Unexpected unknown unit "mk" (unit-no-unknown)
92:20 error Unexpected unit "mk" (unit-whitelist) 

```

I have also checked if the port 127.0.0.1:48126 is being used by another program. But, it is not being used.

Also, why it is not loading configuration from .stylelintrc file?

I am bit confused here.
Thank you

**Comment by jo-sm** [comment]
Can you attach the content of the SCSS file you're using? And can you verify the path of the `.stylelintrc` file, that it's near the same directory as the SCSS file?

**Comment by sethstha** [comment]
@jo-sm 
Finally, found the solution. stylelint_d was globally installed on my pc. Installing it locally solved the problem. It is also loading `.stylelintrc` file. I am still not sure why installing it globally caused the issue. I have also tried to replicate with my office's pc. Same thing happened there. 

Thank you

**Comment by jo-sm** [comment]
Oh, like `npm install -g stylelint_d`?

**Comment by sethstha** [comment]
Yes, installing it using `npm install -g stylelint_d` caused the issue. While installing it locally on my project folder using `npm install stylelint_d` solved this issue. And more thing it also freezes sometime but restarting sublime will go long way.

Also, when it stops working, command `stylelint_d --info` also freezes on terminal.

**Comment by sethstha** [comment]
So, I made a test here. When I first start sublime text and make any mistake on my SCSS file it throws output
```
SublimeLinter: stylelint_d: _preloader.scss ['C:\\xampp\\htdocs\\suffice\\wp-content\\themes\\suffice\\node_modules\\.bin\\stylelint_d.cmd', '--stdin', '--formatter=json', '--file', '@'] 
SublimeLinter: stylelint_d: _preloader.scss ['C:\\xampp\\htdocs\\suffice\\wp-content\\themes\\suffice\\node_modules\\.bin\\stylelint_d.cmd', '--stdin', '--formatter=json', '--file', '@'] 
SublimeLinter: stylelint_d output:
115:33 error Expected single space before "{" (block-opening-brace-space-before) 
```
Again going back to terminal and hitting command `stylelint_d --info` freezes terminal.
Closing terminal and coming back to sublime text and making some mistakes throws output
```
SublimeLinter: stylelint_d: _preloader.scss ['C:\\xampp\\htdocs\\suffice\\wp-content\\themes\\suffice\\node_modules\\.bin\\stylelint_d.cmd', '--stdin', '--formatter=json', '--file', '@'] 
SublimeLinter: stylelint_d: _preloader.scss ['C:\\xampp\\htdocs\\suffice\\wp-content\\themes\\suffice\\node_modules\\.bin\\stylelint_d.cmd', '--stdin', '--formatter=json', '--file', '@']
```
I am running
Windows 10 Version 10.0.14393
Thanks

**Comment by sethstha** [comment]
**Update: Found the problem**

The problem was with the port that stylelint_d listens, I changed the port from `48126` to `49126` on both `stylelint_d.js` and `server.js` and that solved the problem. It's been more than 12 hours and no problem at all.

Thank you

**Comment by jo-sm** [comment]
Really? That's pretty strange... Can you tell me what happens when you switch the ports back to 48126?

**Comment by sethstha** [comment]
I have disabled every plugins i had on sublime except `Sublime Linter`. Again, changed port back to 48126. Now if i remove `semicolon` from any property like `background-color: #fff;`, it throws

```
SublimeLinter: stylelint_d: _header.scss ['C:\\xampp\\htdocs\\suffice\\wp-content\\themes\\suffice\\node_modules\\.bin\\stylelint_d.cmd', '--stdin', '--formatter=json', '--file', '@'] 
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 119, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 929, in lint_view
    linter.lint(hit_time)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\node_linter.py", line 77, in lint
    super(NodeLinter, self).lint(hit_time)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 1397, in lint
    output = self.run(cmd, self.code)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter-contrib-stylelint_d\linter.py", line 57, in run
    error['severity'],
KeyError: 'severity'
 
SublimeLinter: -------------------- 
```
While for other things linting is still working.

**Comment by jo-sm** [comment]
Hi, can you attach your SCSS file and `.stylelintrc` to this issue? I can see the issue from your stack trace but I want to see if there is a bug within Stylelint that is causing this.

**Comment by sethstha** [comment]
Hi, sure here is the SCSS and `.stylelintrc` file 
[file.zip](https://github.com/jo-sm/SublimeLinter-contrib-stylelint_d/files/815860/file.zip)

Thank you

**Comment by jo-sm** [comment]
I just updated to a new version with some fixes and upgrades. Can you see if this fixes the error you're  having?

**Comment by sethstha** [comment]
Hi, jo-sm

Thanks for the effort you made. If definitely made a huge change, Now most of the stylelint configuration are running. Even fixed that old bug i had. 

This solved the problem.
