### ISSUE TITLE
stylelint_d is unresponsive and freezes sublime linter

### ISSUE THREAD

**Issue by sethstha** [jo-sm/SublimeLinter-contrib-stylelint_d#7]
Hi @jo-sm 

I am not sure if this is issue with `stylelint_d` or `sublimeLinter-contrib-stylelint_d`. For me It looks like of `stylelint_d`. Since, you author both of them and this is related to Sublime Linter I am posting here.

In this issue https://github.com/jo-sm/SublimeLinter-contrib-stylelint_d/issues/6 linter used to stop and used to start working after restarting Sublime Text. Now, the problem here is linter becomes unresponsive and freezes Sublime Linter which results stopping other linters too. This occurs within few minutes of linting on `SCSS ` file.

**So, I made a research here.**

- First i restarted Sublime Text and and made some mistakes on my `PHP` file, `PHPCS ` thrown errors right away.
- Second I made some mistakes on  `SCSS`  file, `stylelint_d` freezes there.
- Third I made more mistakes on `PHP` file, `PHPCS` stopped working because `stylelint_d` frozen the `Sublime Linter`
- Fourth I closed Sublime Text ran `stylelint_d.cmd` file from `.bin` folder, It was also unresponsive.

**Here is the console log**
```
SublimeLinter: jshint: content-widget-blog.php ['C:\\Users\\User\\AppData\\Roaming\\npm\\jshint.cmd', '--verbose', '--filename', '@', '--extract=always', '--config', 'C:\\xampp\\htdocs\\suffice\\wp-content\\plugins\\suffice-toolkit\\.jshintrc', '-'] 
SublimeLinter: phpcs: content-widget-blog.php ['C:\\xampp\\php\\phpcs.bat', '--report=checkstyle', '--standard=WordPress'] 
SublimeLinter: phpcs output:
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="2.8.0">
</checkstyle> 
SublimeLinter: jshint: content-widget-blog.php ['C:\\Users\\User\\AppData\\Roaming\\npm\\jshint.cmd', '--verbose', '--filename', '@', '--extract=always', '--config', 'C:\\xampp\\htdocs\\suffice\\wp-content\\plugins\\suffice-toolkit\\.jshintrc', '-'] 
SublimeLinter: stylelint_d: _posts.scss ['C:\\xampp\\htdocs\\suffice\\wp-content\\themes\\suffice\\node_modules\\.bin\\stylelint_d.cmd', '--stdin', '--formatter=json', '--file', '@']
``` 
I haven't got any console log after this

**Here is unresponsive screen when i ran** `stylelint_d.cmd`
![image](https://cloud.githubusercontent.com/assets/2367137/23793632/5af17f50-05b4-11e7-8e01-dca621145452.png)

Thanks

**Comment by jo-sm** [comment]
Hi @sethstha, let me add some debug logging into the `stylelint_d` daemon and then let you try it out with that, so you can more easily pinpoint the issue/allow me to more easily debug what's happening. It's somewhat tricky for me to debug Windows issues (if it's a `stylelint_d` issue, or if it's a Windows specific issue, for example) since I use macOS. In the mean time, can you give me some statistics on your environment: your Sublime version, the SublimeLinter version, the `SublimeLinter-contrib-stylelint_d` version, and your Node version?

**Comment by sethstha** [comment]
Hi @jo-sm 

Thanks for going to add debug logging into the `stylelint_d`

Here is all the information you needed
**OS: Windows 10 10.0.14393
Sublime Text 3 Build 3126
SublimeLinter 3.7.4
stylelint_d 1.0.8
SublimeLinter-contrib-stylelint_d 1.0.8
Node 6.9.4
Npm 3.10.10**

I am always looking forward to helping you, I will also try to debug and find the actual problem.

**Comment by jo-sm** [comment]
Okay, I added some logging into the server process. You just need to update to version `1.0.9`, and restart the server process, and the logging will take effect. 

You'll need to attach to the server process's stdout to see the output (I'm not entirely sure how you would do this on Windows, but on Linux you'd `tail` the process descriptor, and on Mac you'd use Dtrace), but once you do, you should get output like this: 

```
Command received: undefined
No config flag passed
Changing process directory to <directory>
Resolved stylelint in local folder <directory>
Given stdin
Successfully linted
<some JSON output>
```

**Comment by sethstha** [comment]
Hi @jo-sm 

It took me ages to find out how to debug on Windows. I have to read a lot of getting started doc. I used `node-inspector` and `node --debug` 

So the console log while `stylelint_d` was installed locally was
```
Command received: undefined
server.js:95 No config flag passed
server.js:123 Changing process directory to C:/xampp/htdocs/sanjeev/wp-content/themes/sanjeev/assets/sass/site/primary
server.js:137 Could not resolve stylelint in CSS path, using stylelint_d stylelint module
```

After running sublime text and making mistakes node debug broke down with exception of
```
Command received: undefined
No config flag passed
Changing process directory to C:/xampp/htdocs/sanjeev/wp-content/themes/sanjeev/assets/sass/site/primary
Could not resolve stylelint in CSS path, using stylelint_d stylelint module
Given stdin
Successfully linted
net.js:641
    throw new TypeError('invalid data');
    ^

TypeError: invalid data
    at Socket.write (net.js:641:11)
    at Socket.<anonymous> (C:\xampp\htdocs\sanjeev\wp-content\themes\sanjeev\node_modules\stylelint_d\lib\server.js:54:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
```
Also linter didn't worked.

When `stylelint_d` is installed globally the npm debug log was
```
Command received: restart
Command received: undefined
No config flag passed
Changing process directory to C:/xampp/htdocs/sanjeev/wp-content/themes/sanjeev/assets/sass/site/primary
Could not resolve stylelint in CSS path, using stylelint_d stylelint module
Given stdin
Successfully linted
net.js:641
```

Once again debugger broke down with the same exception of
```
Command received: restart
Command received: undefined
No config flag passed
Changing process directory to C:/xampp/htdocs/sanjeev/wp-content/themes/sanjeev/assets/sass/site/primary
Could not resolve stylelint in CSS path, using stylelint_d stylelint module
Given stdin
Successfully linted
net.js:641
 throw new TypeError('invalid data');
    ^

TypeError: invalid data
    at Socket.write (net.js:641:11)
    at Socket.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\stylelint_d\lib\server.js:54:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
```

CLI is working fine when `stylelint_d` is installed `globally`
```
stylelint_d _posts.scss

_posts.scss
 24:15  ×  Missed semicolon   CssSyntaxError
```

**Comment by sethstha** [comment]
Hi @jo-sm 

Here is **good news,** found what is causing `stylelint_d` to stop working on Sublime Text. It is `7365` lines of `style.css`. Whenever I open `style.css` file `sublimeLinter-contrib-stylelint_d` executes the command which freezes `stylelint_d` and thus freezes every `linter` out there.

I have tried adding `/* stylelint-disable */` on head of my `style.css` but it still linting there. 

Is there better approach to exclude file?

Now, You can close this issue. Sorry for the inconvenience

Cheers!

**Update:** used excludes linter setting to exclude `style.css` . Now everything is working fine. I am closing this issue as it is fixed :)

**Comment by sethstha** [comment]
There is also a problem with minified CSS and I am not sure but continuous usage on several `SCSS` files breaks the linter.

While sublime linter has execution timeout of 10s, It should be stopped. There is no problem with CLI or in listening server. I think we need to update linter plugin. Not sure where but something is breaking it. It may be `cmd` or `regex`.

Thanks

**Comment by jo-sm** [comment]
I just updated `stylelint_d` with a bug fix. Does it fix the issue? If not, can you send some sample server logs?

**Comment by sethstha** [comment]
Thanks for the effort @jo-sm 

I think the problem here is with the file size. I will try to explain clearly as possible.

So, I took a time to compare this with `stylelint`.  When i linted `style.css` which has `7365` lines of code with `stylelint` using: 
`$ stylelint style.css`

Which took arround 4.05s and returned all the errors.

Now, I linted same style.css with stylelint_d using:
`$stylelint_d style.css`

Strange thing here is I am getting `Successfully linted` on console but the terminal freezes and I can't get any command of `stylelint_d` to work until I restart npm using `npm restart`

Here is the console log:
```
Received raw data: ["C:\\xampp\\htdocs\\suffice\\wp-content\\themes\\suffice\\assets\\sass\\elements",{"_":["_logos.scss"],"files":["_logos.scss"]}]
server.js:89 Command received: _logos.scss
server.js:120 No config flag passed
server.js:148 Changing process directory to C:/xampp/htdocs/suffice/wp-content/themes/suffice/assets/sass/elements
server.js:162 Could not resolve stylelint in CSS path, using stylelint_d stylelint module
server.js:173 Given files: C:\xampp\htdocs\suffice\wp-content\themes\suffice\assets\sass\elements\_logos.scss
server.js:179 Successfully linted

server.js:62 Received raw data: ["C:\\xampp\\htdocs\\suffice\\wp-content\\themes\\suffice",{"_":["style.css"],"files":["style.css"]}]
server.js:89 Command received: style.css
server.js:120 No config flag passed
server.js:148 Changing process directory to C:/xampp/htdocs/suffice/wp-content/themes/suffice
server.js:162 Could not resolve stylelint in CSS path, using stylelint_d stylelint module
server.js:173 Given files: C:\xampp\htdocs\suffice\wp-content\themes\suffice\style.css
server.js:179 Successfully linted
```

You can see my _logos.scss file is also linted successfully and I am getting error too. But style.css is not giving any output.

I think this is issue with the file size or line `stylelint_d` sends to server.

I am also attaching my style.css file
[style.zip](https://github.com/jo-sm/SublimeLinter-contrib-stylelint_d/files/841132/style.zip)

**Comment by jo-sm** [comment]
Ah, sorry, I meant the initial issue [you commented about here](https://github.com/jo-sm/SublimeLinter-contrib-stylelint_d/issues/7#issuecomment-286059728), did it fix that? 

Let me take a look at the newer issue, thanks for sending the `style.css` file.

**Comment by jo-sm** [comment]
I did find the issue -- it seems that `JSON.stringify` (the method that's taking the data from `stylelint` and sending it to `stylelint_d`) is having an issue transforming the data in memory, and is running out, since it eventually returns a RangeError. I'll investigate handling this using a different library and will reply back when I do.

**Comment by sethstha** [comment]
Thanks, the first issue has been fixed. 👍 

I am also getting the same error on my home PC.
`RangeError: Invalid string length`

Unfortunately, the main issue is still present there. I have excluded my `style.css` from Sublime Linter configuration to prevent it from linting. It is also present when working with multiple files opened in split window.

Is this issue with `stylelint` or `stylelint_d`. However linting with `sublimelinter-contrib-stylelint`, It is slow but throws the output successfully.

Doing quick search lead me to information that opening more than 200mb of `json` file throws this error.

Thank you, I will be waiting for the fix.

**Comment by jo-sm** [comment]
Hey @sethstha, sorry I haven't gotten back to this yet. I tested a little bit last week, but I was running into some issues (using pure JSON leads to node.js crashing, and using `msgpack` takes way too long to be feasible) and I haven't had as much chance to investigate further. I may have a chance to take a look this weekend, but it could be a little bit of time before I find a fix.

In the mean time, I can only recommend not attempting to lint that specific file or any files that are too large (sorry this isn't a good answer ☹️).

**Comment by sethstha** [comment]
Hey @jo-sm 

For me ignoring that file is working fine. It is not good idea but it is doing the trick.
Take your time, we are not in hurry.

**Comment by jo-sm** [comment]
Hi @sethstha, I'm sorry for taking so long to get to this. I've been a bit busy with work and couldn't think of a solution until last night. I was able to figure out a solution, though, and pushed an update this morning should fix the remaining issue here. Can you update to `1.1.0` and test it out?

**Comment by sethstha** [comment]
Hi @jo-sm 

I haven't got much time to investigate. But it seems like it is fixed. Now I am able to lint that huge file too. 
I think you can close this issue.

Kudos to the effort you put to make this awesome linter :)

**Comment by jo-sm** [comment]
Great! 😄

**Comment by sethstha** [comment]
Hi @jo-sm 

I am again back to front-end development and again the linter stopped working. Here is what i got when hitting stylelint_d in command.

```
 memo.outputs[memo.currentIndex][memo.currentType].push(i);
                                           ^

TypeError: Cannot read property 'deprecations' of undefined
    at data.reduce.start (C:\Users\User\AppData\Roaming\npm\node_modules\stylelint_d\bin\stylelint_d.js:128:44)
    at Array.reduce (native)
    at Socket.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\stylelint_d\bin\stylelint_d.js:103:31)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```
