### ISSUE TITLE
stylelint_d disabled. 'cls.defaults' is mandatory and MUST be a dict.

### ISSUE THREAD

**Issue by sb-gravity100** [jo-sm/SublimeLinter-contrib-stylelint_d#8]
**Dunno what to do with this**
`stylelint_d: Defining 'cls.syntax' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.`
`stylelint_d: Defining 'cls.selectors' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.`
`stylelint_d disabled. 'cls.defaults' is mandatory and MUST be a dict.`

**Comment by sb-gravity100** [comment]
### Fixed It

**Comment by adamjohnson** [comment]
I am running into this issue now too. I have the following in my SublimeLinter Settings file:

```json
"stylelint_d": {
  "cls.defaults": {
    "configFile": ".stylelintrc.yml",
    "syntax": "css"
  }
}
```

But that doesn't fix it.

Can you share how you solved your issue?
